### ISSUE TITLE
devnet or testnet

### ISSUE THREAD

**Issue by CRY-D** [0xTaoDev/jupiter-python-sdk#11]
How could I make swaps in devnet?

**Comment by 0xTaoDev** [comment]
Hello, Jupiter doesn't support devnet and testnet, you will need to either simulate the transaction or send it on mainnet directly

**Comment by mubarizkyc** [comment]
@0xTaoDev  @CRY-D  any alternative to test freely

**Comment by crazywowmen** [comment]
+1
