### ISSUE TITLE
Including platform fee

### ISSUE THREAD

**Issue by spacesudo** [0xTaoDev/jupiter-python-sdk#14]
Can we add platform fees on the swap function? Or do I have to do this manually? 
Also is the input amount in Lamport or sol?

**Comment by 0xTaoDev** [comment]
Hello, I added platform fees on the swap function.

The input amount is in integer and you have to factor in the decimals for each token by looking up the decimals for that token. For example, USDC has 6 decimals and 1 USDC is 1000000 in integer when passing it in into the API. (from Jupiter docs)

**Comment by spacesudo** [comment]
Thanks
