### ISSUE TITLE
UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

### ISSUE THREAD

**Issue by sleechie** [0xTaoDev/jupiter-python-sdk#16]
I am very experienced with Python but fairly new to APIs:

result = await async_client.send_raw_transaction(txn=bytes(signed_txn), opts=opts)

returns an error:

UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

but I am using all of the default urls here:

jupiter = Jupiter(
    async_client=async_client,
    keypair=private_key,
    quote_api_url="https://quote-api.jup.ag/v6/quote?",
    swap_api_url="https://quote-api.jup.ag/v6/swap",
    open_order_api_url="https://jup.ag/api/limit/v1/createOrder",
    cancel_orders_api_url="https://jup.ag/api/limit/v1/cancelOrders",
    query_open_orders_api_url="https://jup.ag/api/limit/v1/openOrders?wallet=",
    query_order_history_api_url="https://jup.ag/api/limit/v1/orderHistory",
    query_trade_history_api_url="https://jup.ag/api/limit/v1/tradeHistory"
)

I am not sure if this is the right place for my question, but what exactly am I missing? Thank you so much for putting all of this together!

**Comment by sleechie** [comment]
My bad lol I figured it out

**Comment by 0xTaoDev** [comment]
Hello, how did you fix it? thanks

**Comment by sleechie** [comment]
I never replaced

async_client = AsyncClient("SOLANA-RPC-ENDPOINT-URL")

with an actual endpoint I just left the placeholder string in there. Once I added an endpoint everything worked great. Thanks again for putting this together!

**Comment by 0xTaoDev** [comment]
Thanks, I will make it more clear, have a good day!
