### ISSUE TITLE
Priority? Fees

### ISSUE THREAD

**Issue by kanendosei** [0xTaoDev/jupiter-python-sdk#17]
How do we add priority fees or compute units to this to ensure the transaction is successful?

**Comment by jhliu2019** [comment]
you can add priority_fee parameter by yourself to the method swap() at jupiter.py
Line:645
priority_fee: int=0

and Line:690
transaction_parameters = {
"quoteResponse": quoteResponse,
"prioritizationFeeLamports":priority_fee,  # <- add here
"userPublicKey": user_public_key,
"wrapAndUnwrapSol": wrap_unwrap_sol
}

**Comment by 0xTaoDev** [comment]
Hello, sorry for the delay. I just updated the library, thanks a lot jhliu2019
