### ISSUE TITLE
Solders Issue

### ISSUE THREAD

**Issue by CryptoX78** [0xTaoDev/jupiter-python-sdk#2]
Hi, I can fetch data without authentication, but have run into an issue when trying to execute a swap.

I’m getting these two problems:

import “solders.pubkey” could not be resolved from the  source.
import “solders.keypair” could not be resolved from the source.

i’m running on Windows through VSCode. I’ve tried to resolve playing with python interpreter without success. Also pip list shows solders installed.

What’s the best way to troubleshoot this issue?

**Comment by 0xTaoDev** [comment]
Hello, does the others solders imports works? for example: 
```py
from solders.message import message
from solders.transaction import VersionedTransaction
```

**Comment by CryptoX78** [comment]
Hi, thanks for prompt response, no i’m getting errors for all solders imports. However, I don’t get an import error when just importing solders like below:

`import solders`

I’ve also tried uninstalling and reinstalling solders 0.18.1, which has not resolved the issue.

**Comment by 0xTaoDev** [comment]
Very weird, I never had this problem before, does the files exists in your solders folder package?

**Comment by CryptoX78** [comment]
Yes, the files definitely exit in my solders folder:

`-a----       2024-01-06     12:52           1165 keypair.pyi
-a----       2024-01-06     12:52           6255 message.pyi
-a----       2024-01-06     12:52            814 null_signer.pyi
-a----       2024-01-06     12:52            582 presigner.pyi
-a----       2024-01-06     12:52           1172 pubkey.pyi
`
I tried updating VS Code, but the issue persists!

**Comment by CryptoX78** [comment]
Yes the files definitely exist in my solders folder:

-a----       2024-01-06     12:52           1165 keypair.pyi
-a----       2024-01-06     12:52           6255 message.pyi
-a----       2024-01-06     12:52            814 null_signer.pyi
-a----       2024-01-06     12:52            582 presigner.pyi
-a----       2024-01-06     12:52           1172 pubkey.pyi

I also reinstalled VS code to no avail.

**Comment by 0xTaoDev** [comment]
add me on discord: _taodev_ so we could talk more quickly, if it's right for you
