### ISSUE TITLE
Prioritization Fee Lamports [ERROR]

### ISSUE THREAD

**Issue by nicobullerouge** [0xTaoDev/jupiter-python-sdk#21]
Hi,

I have a problem with priority fees; when I try to pass this argument, it returns an error:

```
async def safe_swap(input_mint: str, output_mint: str, amount: int, slippage_bps: int, prioritization_fee_lamports: int):
    async_client = AsyncClient(rpc_url)
    jupiter = Jupiter(
        async_client=async_client,
        keypair=KEYPAIR,
        quote_api_url=quote_api_url,
        swap_api_url=swap_api_url
    )
    try:
        transaction_data = await jupiter.swap(
            input_mint=input_mint,
            output_mint=output_mint,
            amount=amount,
            slippage_bps=slippage_bps,
            prioritization_fee_lamports=prioritization_fee_lamports
        )
```
        
**Action parsed: swap: An error occurred: Jupiter.swap() got an unexpected keyword argument 'prioritization_fee_lamports'**

```
fyi callback for this arg
        prioritization_fee_lamports = 1500000
``` 

Is it possible to correct? 

Thanks a lot for your great work on this git

**Comment by nicobullerouge** [comment]
@0xTaoDev I saw that you hadn't pushed your version with Priority Fees 

https://pypi.org/project/jupiter-python-sdk/#history 

do you think it's possible to update the sdk with your latest modifications?

**Comment by hgfshfsnjsfgns** [comment]
yep i hope he will push that
