### ISSUE TITLE
Got transaction_id, but swap did not complete.

### ISSUE THREAD

**Issue by Evg20095** [0xTaoDev/jupiter-python-sdk#24]
Thanks for the great job!
I'm using a code snippet, I'm going to exchange sol for usdt, I get a transaction_id, but the swap is not executed, and there is no such transaction in explorer.solana.com.
Can you tell me what this might be connected with?

**Comment by GoodSamoSamo** [comment]
Might need to include a priority fee to ensure it gets picked up and pushed through.

I'm still trying to figure out how to include the priority fee param. It was apparently added, but I keep getting an error when trying to push it through.

https://github.com/0xTaoDev/jupiter-python-sdk/issues/25

**Comment by VovanPower** [comment]
I've already tried all the options, it doesn't work :( what will be the options?

**Comment by jmancool65** [comment]
Adding these parameters to the swap parameters fixed this issue for me : 
             "prioritizationFeeLamports": "auto",
            "dynamicComputeUnitLimit": True,
