### ISSUE TITLE
Swap Transaction string is produced! Are you able to complete the readme example with code to execute the swap transaction?

### ISSUE THREAD

**Issue by oxygenmask23** [0xTaoDev/jupiter-python-sdk#3]
Hi, thank you for writing this python sdk for Jupiter! Are you able to append the execution swap code to the readme code example? 

Thank you!

**Comment by oxygenmask23** [comment]
Figured it out and opened a pull request :)

**Comment by 0xTaoDev** [comment]
Hello, thanks a lot for your help, I'm gonna add it to the readme.md
