### ISSUE TITLE
argument 'keypairs': failed to extract enum Signer

### ISSUE THREAD

**Issue by ghost** [0xTaoDev/jupiter-python-sdk#33]
hello, i have an issue when i want to swap -->argument 'keypairs': failed to extract enum Signer ('KeypairWrapper | PresignerWrapper | NullSignerWrapper')
- variant KeypairWrapper (KeypairWrapper): TypeError: failed to extract field Signer::KeypairWrapper.0, caused by TypeError: 'Signature' object cannot be converted to 'Keypair'
- variant PresignerWrapper (PresignerWrapper): TypeError: failed to extract field Signer::PresignerWrapper.0, caused by TypeError: 'Signature' object cannot be converted to 'Presigner'
- variant NullSignerWrapper (NullSignerWrapper): TypeError: failed to extract field Signer::NullSignerWrapper.0, caused by TypeError: 'Signature' object cannot be converted to 'NullSigner'
i actually use the same code give in the exemple  -->signature = keypair.sign_message(message.to_bytes_versioned(raw_transaction.message)), what's wrong ?

**Comment by gobottai** [comment]
the error came because i tried to rewrite messageV0 to obtain recent blockhash. i fix this.
