### ISSUE TITLE
Error When running script

### ISSUE THREAD

**Issue by octoma** [0xTaoDev/jupiter-python-sdk#7]
Hi. I get the following:::: .local/lib/python3.9/site-packages/jupiter_python_sdk/jupiter.py", line 676, in swap
    transaction_data = httpx.post(url=self.ENDPOINT_APIS_URL['SWAP'], json=transaction_parameters).json()['swapTransaction']
KeyError: 'swapTransactio

**Comment by 0xTaoDev** [comment]
Hello, 
I'm gonna improve the code thanks to the issue you encountered. 
Indeed, this error occurs when there are no routes available. It can happen due to numerous reasons such as: slippage, token not listed, and so on.
I will specificed the reason if there is an error when you are trying to swap.

**Comment by 0xTaoDev** [comment]
Code updated https://github.com/0xTaoDev/jupiter-python-sdk/commit/a9f7d51d2655c29d9ac56c2891385407af82d5ee
